# adapted from https://github.com/flutter/gallery/blob/main/.github/workflows/build.yml

name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["apk --debug", "ios --no-codesign", macos]
    steps:
      # is this necessary? -- sink
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter config --enable-macos-desktop
      - run: flutter doctor -v
      - run: flutter pub get

      - run: flutter build ${{ matrix.target }}
      
      - name: Create .IPA from .APP
        if: contains(matrix.target, 'ios')
        run: |
          mkdir Payload
          mv build/ios/iphoneos/*.app Payload/Miru.app
          zip -r Miru.zip Payload
          mv Miru.zip Miru.ipa
      
      - uses: actions/upload-artifact@v3
        if: contains(matrix.target, 'ios')
        with:
          name: Miru.ipa
          path: Miru.ipa
